FROM nginxinc/nginx-unprivileged:stable-alpine@sha256:15c994d10d6d78658721c3bcafff14cb281fba2a4bdf9d5ba92c416a472516e3
COPY nginx.conf /etc/nginx/nginx.conf
COPY start-proxy.sh /usr/local/bin/start-proxy.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/start-proxy.sh"]
