pid /tmp/nginx.pid;
events {}
http {
  access_log off;
  error_log /dev/stderr warn;
  client_body_temp_path /tmp/client_temp;
  proxy_temp_path /tmp/proxy_temp;
  fastcgi_temp_path /tmp/fastcgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;
  scgi_temp_path /tmp/scgi_temp;

  server {
    listen 8080;
    server_tokens off;
    auth_basic "Jaeger";
    auth_basic_user_file /tmp/jaeger.htpasswd;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Cache-Control "no-store" always;

    location / {
      proxy_pass http://127.0.0.1:16686;
      proxy_set_header Host $host;
      proxy_set_header Authorization "";
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
